### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by renierdbruyn** [alimanfoo/csvvalidator#14]
I would really like to use this library in my project however, if this repo is dead then I doubt that I would be able to due to company policies that would restrict me to do so.

**Comment by cognifloyd** [comment]
see https://github.com/alimanfoo/csvvalidator/pull/12#issuecomment-353649587
> the csvvalidator package is now deprecated and the functionality has been moved to the petl package (see [petl.validate](http://petl.readthedocs.io/en/latest/transform.html#validation)).

**Comment by renierdbruyn** [comment]
Thank you so much. That is exactly what I was looking for!
